### ISSUE TITLE
CUDA error: out of memory

### ISSUE THREAD

**Issue by nimamoradi** [Ichaelus/video-colorization#3]
i want to try to use model on google colab but it give me memory error 
```Colorizing each frame..
Traceback (most recent call last):
  File "colorize_frames.py", line 145, in <module>
    filters = [Colorizer34(gpu=0, weights_path='./pretrained_weights.h5')]
  File "/content/DeOldify/DeOldify/fasterai/filters.py", line 121, in __init__
    super().__init__(gpu=gpu, weights_path=weights_path, nf_factor=nf_factor, map_to_orig=map_to_orig)
  File "/content/DeOldify/DeOldify/fasterai/filters.py", line 83, in __init__
    self.model = self._get_model(nf_factor=nf_factor, gpu=gpu)
  File "/content/DeOldify/DeOldify/fasterai/filters.py", line 124, in _get_model
    return Unet34(nf_factor=nf_factor).cuda(gpu)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 258, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  [Previous line repeated 1 more time]
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 191, in _apply
    param.data = fn(param.data)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 258, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: out of memory
Colorizing frames failed```
can't seem to generate images with render_factor = 30 or even as low as 10, whereas i can gen images with render_factor more 30 with original deoldify

**Comment by Ichaelus** [comment]
Hi nimamoradi,
thank you for reporting this issue.

Sadly I can't look into it right now because of a faulty GPU card, but I'll report back once I got it back up running.

I did never try to run this script on google colab, but I assume that it would break the memory limitations of their free plan pretty soon. Maybe that is what happened to you.

Best regards,
Ichaelus

**Comment by Ichaelus** [comment]
Closing this, video processing will always require somehow beefy hardware.
